# Generated by Django 5.1.4 on 2025-01-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usermodel_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='full_name',
            field=models.CharField(default='', max_length=266),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='location',
            field=models.CharField(default='', max_length=266),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
